### ISSUE TITLE
Switch from Secp256k1 to Curve25519 or Curve448

### ISSUE THREAD

**Issue by mswilkison** [zerodb/zerodb#17]
Both are now an official standards: https://www.rfc-editor.org/info/rfc7748

**Comment by michwill** [comment]
I believe, Curve25519 makes sense by default since it's the fastest and de-facto standard of ECC these days. 448 is also [safe](https://safecurves.cr.yp.to/) but 3 times slower iirc

**Comment by michwill** [comment]
Actually, we use asymmetric crypto only during auth, so performance doesn't matter. That becomes unnecessary when we wrap everything into SSL (which we should do, even though everything is already encrypted) (so, particular crypto parameters will be a part of the certificate)

**Comment by michwill** [comment]
Using standard SSL now
