### ISSUE TITLE
Use SSL on top of our encryption between client and server

### ISSUE THREAD

**Issue by michwill** [zerodb/zerodb#22]
On top of encryption we have, we need to use SSL in order to prevent access patterns analysis by random observers.
This will change the auth as well. It will likely be a client-side certificate (self-signed with pubkey stored on the server, or signed by server, or derived from a passphrase). AES key is going to be derived from either passphrase or client certificate private key.

To contributors: please feel free to add any comments on the best way of doing that and why.
We want to have an easy way of either just having a passphrase or having a client certificate

**Comment by xueyumusic** [comment]
Client certificate authentication may need a way to sync the client certificates when the users access the server from different client machines. This way also need certificates management which seems complex

**Comment by michwill** [comment]
Fixed with ZEO5
