### ISSUE TITLE
website down

### ISSUE THREAD

**Issue by sscarduzio** [zerodb/zerodb#59]
Is this abandonware?

**Comment by mswilkison** [comment]
ZeroDB the company has become NuCypher (https://github.com/nucypher). We're not maintaining this project (if someone is, ping us). Instead we are focused on the proxy re-encryption aspect of ZeroDB.

**Comment by traverseda** [comment]
It would still be a lot better if you did some basic maintence before EOLing this codebase. Not doing those basics makes me a lot less likely to trust future open-source offerings from your company. It's fine to EOL a product, but I can't recomend my company use *any* of your projects if this is *how* you EOL a product.

You should

 * Put a clear warning that this project is no longer going to be maintained

 * Remove broken links

 * Where possible, convert things that were on the website into static resources, like github pages

 * Say that you are looking for a new maintainer, and if someone steps up, hand control of the repository over to them

**Comment by mswilkison** [comment]
@traverseda thanks for your suggestions, which I've incorporated.
